#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SuiviAGAndroid.Resource", IsApplication=true)]

namespace SuiviAGAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int AGResidenceAdresseLabel = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int AGResidenceNameLabel = 2131034112;
			
			// aapt resource value: 0x7f05000b
			public const int AddAGResidenceButton = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int MainHeader = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int btnAGResidenceCancelDelete = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int btnAGResidenceSave = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int listResidence = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int lstItemAGResidence = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int txtAGResidenceAdresse = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int txtAGResidenceName = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int txtAdresse = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int txtName = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AGResidenceDetails = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AGResidenceListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AGTravauxListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
