#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SuiviAGAndroid.Resource", IsApplication=true)]

namespace SuiviAGAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ArrowBack = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Search = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int AGResidenceAdresseLabel = 2131034115;
			
			// aapt resource value: 0x7f05000d
			public const int AGResidenceLabel = 2131034125;
			
			// aapt resource value: 0x7f05001b
			public const int AGResidenceLayout = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int AGResidenceName = 2131034140;
			
			// aapt resource value: 0x7f050000
			public const int AGResidenceNameLabel = 2131034112;
			
			// aapt resource value: 0x7f050014
			public const int AGTravauxAvancementLabel = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int AGTravauxAvancementSeekBar = 2131034133;
			
			// aapt resource value: 0x7f050012
			public const int AGTravauxDateEcheanceLabel = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int AGTravauxDateVoteLabel = 2131034128;
			
			// aapt resource value: 0x7f05000b
			public const int AGTravauxMotifLabel = 2131034123;
			
			// aapt resource value: 0x7f050016
			public const int AGTravauxNoteLabel = 2131034134;
			
			// aapt resource value: 0x7f050030
			public const int AddAGTravauxButton = 2131034160;
			
			// aapt resource value: 0x7f050029
			public const int Avancement = 2131034153;
			
			// aapt resource value: 0x7f050027
			public const int AvancementLabel = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int AvancementValue = 2131034152;
			
			// aapt resource value: 0x7f050025
			public const int DateEcheance = 2131034149;
			
			// aapt resource value: 0x7f050024
			public const int DateEcheanceLabel = 2131034148;
			
			// aapt resource value: 0x7f050023
			public const int DateEcheanceLayout = 2131034147;
			
			// aapt resource value: 0x7f050022
			public const int DateVote = 2131034146;
			
			// aapt resource value: 0x7f050021
			public const int DateVoteLabel = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int DateVoteLayout = 2131034144;
			
			// aapt resource value: 0x7f050001
			public const int MainHeader = 2131034113;
			
			// aapt resource value: 0x7f05001f
			public const int Motif = 2131034143;
			
			// aapt resource value: 0x7f05001e
			public const int MotifLabel = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int MotifLayout = 2131034141;
			
			// aapt resource value: 0x7f050005
			public const int btnAGResidenceCancelDelete = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int btnAGResidenceSave = 2131034118;
			
			// aapt resource value: 0x7f05002c
			public const int btnAGSrc = 2131034156;
			
			// aapt resource value: 0x7f050018
			public const int btnAGTravauxCancelDelete = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int btnAGTravauxSave = 2131034137;
			
			// aapt resource value: 0x7f05002b
			public const int layoutAGSrc = 2131034155;
			
			// aapt resource value: 0x7f050026
			public const int linearLayout1 = 2131034150;
			
			// aapt resource value: 0x7f05000a
			public const int listResidence = 2131034122;
			
			// aapt resource value: 0x7f05002a
			public const int listTravaux = 2131034154;
			
			// aapt resource value: 0x7f05002f
			public const int lstAGResidenceButton = 2131034159;
			
			// aapt resource value: 0x7f05002e
			public const int lstAGTravauxButton = 2131034158;
			
			// aapt resource value: 0x7f050007
			public const int lstItemAGResidence = 2131034119;
			
			// aapt resource value: 0x7f05001a
			public const int lstItemAGTravaux = 2131034138;
			
			// aapt resource value: 0x7f05000f
			public const int txtAGResidence = 2131034127;
			
			// aapt resource value: 0x7f050004
			public const int txtAGResidenceAdresse = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int txtAGResidenceName = 2131034114;
			
			// aapt resource value: 0x7f05002d
			public const int txtAGSrc = 2131034157;
			
			// aapt resource value: 0x7f050013
			public const int txtAGTravauxDateEcheance = 2131034131;
			
			// aapt resource value: 0x7f050011
			public const int txtAGTravauxDateVote = 2131034129;
			
			// aapt resource value: 0x7f05000c
			public const int txtAGTravauxMotif = 2131034124;
			
			// aapt resource value: 0x7f050017
			public const int txtAGTravauxNote = 2131034135;
			
			// aapt resource value: 0x7f05000e
			public const int txtAGTravauxmotif = 2131034126;
			
			// aapt resource value: 0x7f050009
			public const int txtAdresse = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int txtName = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AGResidenceDetails = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AGResidenceListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AGResidenceListScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int AGTravauxDetails = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int AGTravauxListItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int AGTravauxListScreen = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
